version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: backend/todo
      dockerfile: Dockerfile
    ports: [ 8090 ] # now it is only accsessible inside if the network
    networks:
      - todo_network

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=/api
    ports:
      - "3001:3000"
    networks:
      - todo_network
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
