CREATE TABLE IF NOT EXISTS "todo_items"
(
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "todo_item_name" VARCHAR(255) NOT NULL,
    "priority"       INT          NOT NULL
);